services:
  frontend:
    build: 
      context: ./frontend
    container_name: kupipodariday-frontend
    ports:
      - "8081:80"
    env_file:
      - frontend/.env
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    container_name: kupipodariday-backend
    ports:
      - "4000:3000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - backend/.env
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    container_name: kupipodariday-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 